import time
print("choose Website (ex. usa.gov)")
site = input()
print("Good, which botnet do you want to use? (Filter Most to less)")
print("Foxsoc.service (1.7M devices and 2M Lines of code)")
print("Idosing.service (764K devices and 253K lines of code)")
print("Ydos.service (567K devices 500K lines of code)")
print("ddos.service (387K devices 30 lines of code recommended)")
botnet = input()
print("Great! wait while " + botnet + " is doing their work! (Est. 30sec-2min)")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(2)
print("DDoSing " + site + ". 200 OK")
time.sleep(5)
print("DDoS finished! 503 Service Unavailable")
time.sleep(2)